Sprint 4
PushaDi/MovieQuiz-ios pull request #1
Opened 2022-09-16 16:26 UTC by PushaDi

К сожалению, в связи с каким-то багом в xCode, кастомные шрифты добавляются, но не могут быть использованы в инспекторе при редактировании сторибордов.
В связи с этим, шрифты были изменены уже в коде.

2022-09-16 18:06 UTC, ABashkirova requested changes
Привет! 

Хорошая работа, есть несколько недочетов, которые нужно исправить (см ответ в системе)

2022-09-16 18:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Заметьте, что здесь вы вызываете отложенный (асинхронный) код. Который исполнится через 1 секунду.
За одну секунду пользователь может еще пару раз жмякнуть по кнопке ответа, и вы вызовете еще несколько таких отложенных функций, не контролируя счетчики верных ответов и индекс текущего вопроса.
<img width="549" alt="Screenshot 2022-09-16 at 20 28 34" src="https://user-images.githubusercontent.com/20269264/190703092-87794f5c-efb9-4c2a-9d61-887f16d50ca7.png">

2022-09-16 18:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
Я верю, что в Xcode могло что-то пойти не так, и шрифты не выбрались. (к сожалению, не без багов даже Apple!).

Проверьте, что вы сменили у шрифта тип на Custom, затем проверьте, что в списке действительно нет YPDisplay. С вашим проектом все верно на моем устройстве и его выбрать можно. 
В крайнем случае еще можно попробовать выключить Xcode и включить заново (и иногда даже советуют перезагрузить систему 😄). 
<img width="1550" alt="Screenshot 2022-09-16 at 20 32 12" src="https://user-images.githubusercontent.com/20269264/190703356-79e276ff-24e3-47aa-9131-f8e70eedec09.png">

2022-09-19 06:53 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet  weak var previewImageView: UIImageView!
Исправлено

2022-09-19 07:15 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
<img width="317" alt="Снимок экрана 2022-09-19 в 09 59 16" src="https://user-images.githubusercontent.com/93981199/190966785-6b25ca92-5210-4d80-982d-65909adb5ea8.png">
Увы, никак. Я даже переустановил полностью xCode

2022-09-19 07:20 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
Шрифт должен быть в начале списка

2022-09-19 07:24 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
Окей, я передам команде авторов! Спасибо что сообщили :)

2022-09-19 07:24 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
Еще момент: а в систему шрифт установлен?

2022-09-19 14:53 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionLabel.font = UIFont(name: "YSDisplay-Bold", size: 23)
да, тогда он появляется при выборе текста Attributed.
Но, почему-то, при таком способе, при симуляции я его не видел

2022-09-19 14:55 UTC, merged