Untitled Pull Request
PushaDi/MovieQuiz-ios pull request #3
Opened 2022-10-18 08:27 UTC by PushaDi

Homework_sprint_06

2022-10-18 14:16 UTC, ABashkirova requested changes
Обязательно надо поправить retain cycl'ы, и добавить пропущенный private 

остальное по желанию

2022-10-18 14:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
Здесь ни в коем случае не надо было избавляться от `weak var`, так вы создаете утечку памяти :(

2022-10-18 14:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
Старайтесь захватывать слабо ссылку на себя как можно выше. Тут контекст будет захвачен сначала сильно (оно нам не надо), потом будет ослаблен на главной очереди. Порядок не тот, который ожидается
```suggestion
        moviesLoader.loadMovies { [weak self] result in
            DispatchQueue.main.async { [weak self] in
```

2022-10-18 14:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    print("Failed to load image")
очень хорошо! 

Однако здесь еще нужно выйти из функции, иначе сработает сначала delegate.didFailToLoadData, а затем delegate.didReceiveNextQuestion

2022-10-18 14:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate.didReceiveNextQuestion(question: question)
В одну строчку же лучше, нет? :) 
```suggestion
                self?.delegate.didReceiveNextQuestion(question: question)
```

2022-10-19 06:00 UTC, PushaDi commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
в этом случае, пришлось добавить к протоколу делегата, что он конформится к AnyObject - так правильно?

2022-10-19 06:06 UTC, PushaDi commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate.didReceiveNextQuestion(question: question)
Оно конечно лучше, но я думал, что guard let обязательно в таких случаях))

2022-10-19 06:36 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate.didReceiveNextQuestion(question: question)
В данном случае про удобство. Иногда вам нужен доступ к переменным self, чтобы передать переменную в качестве параметра функции self. Тогда чтобы с националами не работать, проще разыменовать и работать с сильной ссылкой. 
Это не ошибка, можно оставит :) скорее дело вкуса, мне такой вариант кажется чище, а кто-то возразит 🙃

2022-10-19 07:08 UTC, PushaDi commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
В плане, что в ответ может прийти что-то с ошибкой и пустым массивом?

2022-10-19 08:05 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Да, например такие кейсы:

API-key не верный (устарел), или количество запросов в день превышено (до 100 запросов можно отправить). 
Тогда сервис возвращает вам ошибку и пустой массив

2022-10-19 19:33 UTC, ABashkirova approved these changes
Отличная работа :)

2022-10-19 19:33 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//    }
Если не нужен, надо бы почистить

2022-10-20 08:11 UTC, merged