Homework_sprint_7
PushaDi/MovieQuiz-ios pull request #5
Opened 2022-11-11 05:44 UTC by PushaDi

Окончание работы над дз
Полностью переделано сообщение под паттерн MVP
Написаны тесты

2022-11-11 12:34 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        ].joined(separator: "\n")
так тоже нормально, но есть еще тройные кавычки, может потом пригодятся: 
```
let banner = """
          __,
         (           o  /) _/_
          `.  , , , ,  //  /
        (___)(_(_/_(_ //_ (__
                     /)
                    (/
        """
```

2022-11-11 12:47 UTC, mmbabaev requested changes
Нужно испрвить UIAlertAction

2022-11-11 12:47 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
у фабрики и сервиса опционалы больше не нужны

2022-11-11 12:47 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
тк в init инициализируем их

2022-11-11 12:47 UTC, mmbabaev commented on MovieQuizPresenterTests/MovieQuizPresenterTests.swift
> +        let viewModel = sut.convert(model: question)
Если есть желание, предлагаю немного улучшить, уже создан `MovieQuizViewControllerProtocolMock`: 

1) Вообще функция convert может быть приватной, она не используется в vc
2) Тогда нужно можно проверить ее косвенно. Проверим метод `didReceiveNextQuestion` 
3) Нужно проверить, что vc получил ожидаемую viewModel. Для этого в моке `func show(quiz step: QuizStepViewModel)` нужно сохранять step в отдельное свойство
4) В тесте вызываем `didReceiveNextQuestion`, затем достаем `viewModel` из мок vc, проверяем его

2022-11-11 12:47 UTC, mmbabaev commented on MovieQuizUITests/MovieQuizUITests.swift
> +        XCTAssertFalse(firstPoster == secondPoster)
Необязательно для исправления, есть неточность в материалах (уже исправляем).

Здесь мы сравниваем XCUIElement XCTAssertFalse(firstPoster == secondPoster)  , но так делать неправильно.
При получении XCUIElement из query скорее всего создается новый экземпляр элемента. Поэтому, если не нажимать на кнопку да, то тест все равно пройдет успешно.

на скрине видно, что адреса объектов разные
￼
Здесь описан вариант решения
![sleep(2)](https://user-images.githubusercontent.com/12600807/201342678-eb55b0f2-0d81-4077-b38d-715434c781ef.png)

https://askcodes.net/coding/xcuielement---obtain-image-value

2022-11-11 12:47 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        let alertAction = UIAlertAction(title: errorModel.buttonText, style: .default) { [weak self] _ in
лучше не создавать UIAlertAction здесь. Нужно максимально абстрагировать этот Presenter (бизнес логику модуля) от UIKit. Вы можете передать completion в AlertModel и создавать `UIAlertAction` в `AlertPresenter`

2022-11-11 14:09 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        ].joined(separator: "\n")
знаю, изначально так и было)
А вот в последнем спринте предложили делать так, чтобы генерировать проще было)
Но, согласен, читалось бы проще с кавычками

2022-11-11 14:11 UTC, PushaDi commented on MovieQuizUITests/MovieQuizUITests.swift
> +            sleep(3)
да, согласен, просто с 1 секундой не проходило, не успевали подгрузиться новые вопросы иногда

2022-11-11 14:12 UTC, PushaDi commented
> Нужно испрвить UIAlertAction

Правильно я понимаю, что основное, что нужно поправить - это?

> лучше не создавать UIAlertAction здесь. Нужно максимально абстрагировать этот Presenter (бизнес логику модуля) от UIKit. Вы можете передать completion в AlertModel и создавать UIAlertAction в AlertPresenter

2022-11-11 22:24 UTC, mmbabaev commented
> 

Да

2022-11-11 22:25 UTC, mmbabaev commented on MovieQuizUITests/MovieQuizUITests.swift
> +            sleep(3)
Окей

2022-11-11 22:25 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        ].joined(separator: "\n")
Окей, так тоже нормально

2022-11-14 11:26 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
у фабрики пришлось оставить, иначе ругается в ините, что мы используем self до его инициализации

2022-11-14 12:55 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        let alertAction = UIAlertAction(title: errorModel.buttonText, style: .default) { [weak self] _ in
Пришлось избавиться от изначальной логики, которая немного отличалась от учебника (хотел сохранять прогресс в тесте при сбое сети во время игры).
При передаче completion через AlertModel, Xcode ругался, что он, completion, не используется

2022-11-15 21:53 UTC, mmbabaev requested changes

2022-11-15 21:53 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
хорошо, в принципе можно было не добавлять delegate как аргумент конструктора и проставлять его как свойство

2022-11-15 21:53 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var viewController: MovieQuizViewControllerProtocol
вы убрали модификатор weak, появился retain cycle. Нужно вернуть как было

2022-11-15 21:53 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let alertAction = UIAlertAction(title: errorModel.buttonText, style: .default) { [weak self] _ in
1) нужно создавать UIAlertAction в AlertPresenter
2) при содании AlertModel в Presenter передавать в completion` { restartQuiz() }`
3) При создании UIAlertAction вызывать `alertModel.completion`

2022-11-15 21:53 UTC, mmbabaev commented on MovieQuizPresenterTests/MovieQuizPresenterTests.swift
> +        let viewModel = viewControllerMock.viewModel
из-за Dispatch.main.async не успеваем отработать вызов `viewController.show`. 

Если опциональное задание не получается сделать, то лучше оставить старый вариант. Прохождение всех тестов - обязательное условие

Решение с ожиданием expectation:
```
//
//  MovieQuizPresenterTests.swift
//  MovieQuizPresenterTests
//
//  Created by DMITRY KHLOPTSOV on 11.11.2022.
//

import XCTest

@testable import MovieQuiz

final class MovieQuizViewControllerProtocolMock: MovieQuizViewControllerProtocol {
    
    var viewModel: QuizStepViewModel = MovieQuiz.QuizStepViewModel(image: UIImage(), question: "", questionNumber: "")
  var expectation: XCTestExpectation!
    
    func showNetworkError(errorModel: MovieQuiz.AlertModel) {
        
    }
    
    func enableButtons() {
        
    }
    
    func disableButtons() {
        
    }
    
    func show(quiz step: MovieQuiz.QuizStepViewModel) {
        self.viewModel = step
      self.expectation.fulfill()
    }

    func show(quiz result: MovieQuiz.QuizResultsViewModel) {
        
    }

    func highlightImageBorder(isCorrect: Bool) {
        
    }

    func showLoadingIndicator() {
        
    }

    func hideLoadingIndicator() {
        
    }

    func showNetworkError(errorModel: MovieQuiz.AlertModel, action: UIAlertAction) {
        
    }
}

final class MovieQuizPresenterTests: XCTestCase {
    func testPresenterConvertModel() throws {
      let expectation = expectation(description: "wait for async")
        let viewControllerMock = MovieQuizViewControllerProtocolMock()
      viewControllerMock.expectation = expectation
        let sut = MovieQuizPresenter(viewController: viewControllerMock)
        
        let emptyData = Data()
        let question = QuizQuestion(image: emptyData, text: "Question Text", correctAnswer: true)
        
        sut.didReceiveNextQuestion(question: question)
        

        wait(for: [expectation], timeout: 1)

      let viewModel = viewControllerMock.viewModel
        XCTAssertNotNil(viewModel.image)
        XCTAssertEqual(viewModel.question, "Question Text")
        XCTAssertEqual(viewModel.questionNumber, "1/10")
    }
}
```

2022-11-15 22:17 UTC, mmbabaev requested changes

2022-11-15 22:17 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let message = presenter?.makeResultMessage()
makeResultMessage() вызывается два раза. Из-за этого количество игр прибавляется на 2 после одного раунда, нужно исправить и вызывать один раз

2022-11-16 05:03 UTC, PushaDi commented on MovieQuizPresenterTests/MovieQuizPresenterTests.swift
> +        let viewModel = viewControllerMock.viewModel
Про то, что это обязательно условие - знаю, но в этот раз оставил не работающее специально, чтобы показать, что именно не работает

2022-11-16 06:21 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                    message: message,
было message, полученное из повторного вызова makeResultMessage из презента.
Из-за этого в итоге и был косяк с двойным увеличением числа пройденных квизов

2022-11-16 06:43 UTC, PushaDi commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let alertAction = UIAlertAction(title: errorModel.buttonText, style: .default) { [weak self] _ in
Исправлено

2022-11-16 07:58 UTC, mmbabaev approved these changes

2022-11-16 08:53 UTC, merged